version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=papa1976igor
      - POSTGRES_DB=education_app
    ports:
      - "5433:5433"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=papa1976igor
      - POSTGRES_DB=education_app_test
    ports:
      - "5434:5434"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - custom
networks:
  custom:
    driver: bridge
